package tech.picnic.errorprone.refasterrules;

import java.lang.reflect.Field;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.FieldSource;
import org.openrewrite.*;

import static org.openrewrite.java.Assertions.java;

import org.openrewrite.java.Assertions;
import org.openrewrite.java.JavaIsoVisitor;
import org.openrewrite.java.JavaParser;
import org.openrewrite.java.JavaTemplate;
import org.openrewrite.java.tree.J;
import org.openrewrite.test.RewriteTest;
import org.openrewrite.test.TypeValidation;

public class TemplateTest implements RewriteTest {
    static List<String> code = new ArrayList<>();

    static List<String> recipes = List.of(
            "AssertJShortRulesRecipes.AbstractShortAssertIsEqualToRecipe",
            "AssertJShortRulesRecipes.AbstractShortAssertIsNotEqualToRecipe",
            "AssertJShortRulesRecipes.AbstractShortAssertIsNotZeroRecipe",
            "AssertJShortRulesRecipes.AbstractShortAssertIsOneRecipe",
            "AssertJShortRulesRecipes.AbstractShortAssertIsZeroRecipe",
            "AssertJComparableRulesRecipes.AssertThatIsEqualByComparingToRecipe",
            "AssertJComparableRulesRecipes.AssertThatIsGreaterThanRecipe",
            "AssertJComparableRulesRecipes.AssertThatIsGreaterThanOrEqualToRecipe",
            "AssertJComparableRulesRecipes.AssertThatIsLessThanRecipe",
            "AssertJComparableRulesRecipes.AssertThatIsLessThanOrEqualToRecipe",
            "AssertJComparableRulesRecipes.AssertThatIsNotEqualByComparingToRecipe",
            "StreamRulesRecipes.ConcatOneStreamRecipe",
            "StreamRulesRecipes.ConcatTwoStreamsRecipe",
            "StreamRulesRecipes.EmptyStreamRecipe",
            "StreamRulesRecipes.FilterOuterStreamAfterFlatMapRecipe",
            "StreamRulesRecipes.FlatMapOuterStreamAfterFlatMapRecipe",
            "StreamRulesRecipes.JoiningRecipe",
            "StreamRulesRecipes.MapOuterStreamAfterFlatMapRecipe",
            "StreamRulesRecipes.StreamAllMatchRecipe",
            "StreamRulesRecipes.StreamAllMatch2Recipe",
            "StreamRulesRecipes.StreamAnyMatchRecipe",
            "StreamRulesRecipes.StreamCountRecipe",
            "StreamRulesRecipes.StreamFilterCollectRecipe",
            "StreamRulesRecipes.StreamFilterSortedRecipe",
            "StreamRulesRecipes.StreamFilterSortedWithComparatorRecipe",
            "StreamRulesRecipes.StreamFindAnyIsEmptyRecipe",
            "StreamRulesRecipes.StreamFindAnyIsPresentRecipe",
            "StreamRulesRecipes.StreamFlatMapCollectRecipe",
            "StreamRulesRecipes.StreamIterateRecipe",
            "StreamRulesRecipes.StreamMapCollectRecipe",
            "StreamRulesRecipes.StreamMapFilterRecipe",
            "StreamRulesRecipes.StreamMapFirstRecipe",
            "StreamRulesRecipes.StreamMapToDoubleSumRecipe",
            "StreamRulesRecipes.StreamMapToDoubleSummaryStatisticsRecipe",
            "StreamRulesRecipes.StreamMapToIntSumRecipe",
            "StreamRulesRecipes.StreamMapToIntSummaryStatisticsRecipe",
            "StreamRulesRecipes.StreamMapToLongSumRecipe",
            "StreamRulesRecipes.StreamMapToLongSummaryStatisticsRecipe",
            "StreamRulesRecipes.StreamMaxRecipe",
            "StreamRulesRecipes.StreamMaxNaturalOrderRecipe",
            "StreamRulesRecipes.StreamMinRecipe",
            "StreamRulesRecipes.StreamMinNaturalOrderRecipe",
            "StreamRulesRecipes.StreamNoneMatchRecipe",
            "StreamRulesRecipes.StreamNoneMatch2Recipe",
            "StreamRulesRecipes.StreamOf1Recipe",
            "StreamRulesRecipes.StreamOf2Recipe",
            "StreamRulesRecipes.StreamOf3Recipe",
            "StreamRulesRecipes.StreamOf4Recipe",
            "StreamRulesRecipes.StreamOf5Recipe",
            "StreamRulesRecipes.StreamOfArrayRecipe",
            "StreamRulesRecipes.StreamOfNullableRecipe",
            "StreamRulesRecipes.StreamReduceRecipe",
            "StreamRulesRecipes.StreamReduceWithIdentityRecipe",
            "StreamRulesRecipes.StreamTakeWhileRecipe",
            "StreamRulesRecipes.StreamsConcatRecipe",
            "ImmutableListRulesRecipes.ImmutableListBuilderRecipe",
            "ImmutableListRulesRecipes.ImmutableListOfRecipe",
            "ImmutableListRulesRecipes.ImmutableListOf1Recipe",
            "ImmutableListRulesRecipes.ImmutableListOf2Recipe",
            "ImmutableListRulesRecipes.ImmutableListOf3Recipe",
            "ImmutableListRulesRecipes.ImmutableListOf4Recipe",
            "ImmutableListRulesRecipes.ImmutableListOf5Recipe",
            "ImmutableListRulesRecipes.ImmutableListSortedCopyOfRecipe",
            "ImmutableListRulesRecipes.ImmutableListSortedCopyOfWithCustomComparatorRecipe",
            "ImmutableListRulesRecipes.IterableToImmutableListRecipe",
            "ImmutableListRulesRecipes.StreamToDistinctImmutableListRecipe",
            "ImmutableListRulesRecipes.StreamToImmutableListRecipe",
            "SuggestedFixRulesRecipes.SuggestedFixDeleteRecipe",
            "SuggestedFixRulesRecipes.SuggestedFixPostfixWithRecipe",
            "SuggestedFixRulesRecipes.SuggestedFixPrefixWithRecipe",
            "SuggestedFixRulesRecipes.SuggestedFixReplaceStartEndRecipe",
            "SuggestedFixRulesRecipes.SuggestedFixReplaceTreeRecipe",
            "SuggestedFixRulesRecipes.SuggestedFixReplaceTreeStartEndRecipe",
            "SuggestedFixRulesRecipes.SuggestedFixSwapRecipe",
            "AssertJFloatRulesRecipes.AbstractFloatAssertIsCloseToWithOffsetRecipe",
            "AssertJFloatRulesRecipes.AbstractFloatAssertIsEqualToRecipe",
            "AssertJFloatRulesRecipes.AbstractFloatAssertIsNotEqualToRecipe",
            "AssertJFloatRulesRecipes.AbstractFloatAssertIsNotZeroRecipe",
            "AssertJFloatRulesRecipes.AbstractFloatAssertIsOneRecipe",
            "AssertJFloatRulesRecipes.AbstractFloatAssertIsZeroRecipe",
            "PreconditionsRulesRecipes.CheckArgumentRecipe",
            "PreconditionsRulesRecipes.CheckArgumentWithMessageRecipe",
            "PreconditionsRulesRecipes.CheckElementIndexWithMessageRecipe",
            "PreconditionsRulesRecipes.CheckPositionIndexRecipe",
            "PreconditionsRulesRecipes.CheckPositionIndexWithMessageRecipe",
            "PreconditionsRulesRecipes.CheckStateRecipe",
            "PreconditionsRulesRecipes.CheckStateWithMessageRecipe",
            "PreconditionsRulesRecipes.RequireNonNullRecipe",
            "PreconditionsRulesRecipes.RequireNonNullStatementRecipe",
            "PreconditionsRulesRecipes.RequireNonNullWithMessageRecipe",
            "PreconditionsRulesRecipes.RequireNonNullWithMessageStatementRecipe",
            "ImmutableSortedMapRulesRecipes.EmptyImmutableSortedMapRecipe",
            "ImmutableSortedMapRulesRecipes.EntryToImmutableSortedMapRecipe",
            "ImmutableSortedMapRulesRecipes.ImmutableSortedMapBuilderRecipe",
            "ImmutableSortedMapRulesRecipes.ImmutableSortedMapNaturalOrderBuilderRecipe",
            "ImmutableSortedMapRulesRecipes.ImmutableSortedMapReverseOrderBuilderRecipe",
            "ImmutableSortedMapRulesRecipes.IterableToImmutableSortedMapRecipe",
            "ImmutableSortedMapRulesRecipes.PairToImmutableSortedMapRecipe",
            "AssertJBooleanRulesRecipes.AbstractBooleanAssertIsEqualToRecipe",
            "AssertJBooleanRulesRecipes.AbstractBooleanAssertIsFalseRecipe",
            "AssertJBooleanRulesRecipes.AbstractBooleanAssertIsNotEqualToRecipe",
            "AssertJBooleanRulesRecipes.AbstractBooleanAssertIsTrueRecipe",
            "AssertJBooleanRulesRecipes.AssertThatBooleanIsFalseRecipe",
            "AssertJBooleanRulesRecipes.AssertThatBooleanIsTrueRecipe",
            "ReactorRulesRecipes.ConcatMapIterableIdentityRecipe",
            "ReactorRulesRecipes.ConcatMapIterableIdentityWithPrefetchRecipe",
            "ReactorRulesRecipes.ContextEmptyRecipe",
            "ReactorRulesRecipes.FluxAsStepVerifierExpectNextRecipe",
            "ReactorRulesRecipes.FluxCastRecipe",
            "ReactorRulesRecipes.FluxCollectToImmutableListRecipe",
            "ReactorRulesRecipes.FluxCollectToImmutableSetRecipe",
            "ReactorRulesRecipes.FluxConcatMapRecipe",
            "ReactorRulesRecipes.FluxConcatMapIterableRecipe",
            "ReactorRulesRecipes.FluxConcatMapIterableWithPrefetchRecipe",
            "ReactorRulesRecipes.FluxConcatMapWithPrefetchRecipe",
            "ReactorRulesRecipes.FluxCountMapMathToIntExactRecipe",
            "ReactorRulesRecipes.FluxDefaultIfEmptyRecipe",
            "ReactorRulesRecipes.FluxDeferredErrorRecipe",
            "ReactorRulesRecipes.FluxDoOnErrorRecipe",
            "ReactorRulesRecipes.FluxEmptyRecipe",
            "ReactorRulesRecipes.FluxErrorSupplierRecipe",
            "ReactorRulesRecipes.FluxFilterSortRecipe",
            "ReactorRulesRecipes.FluxFilterSortWithComparatorRecipe",
            "ReactorRulesRecipes.FluxFromIterableRecipe",
            "ReactorRulesRecipes.FluxFromStreamSupplierRecipe",
            "ReactorRulesRecipes.FluxJustRecipe",
            "ReactorRulesRecipes.FluxMapRecipe",
            "ReactorRulesRecipes.FluxMapNotNullRecipe",
            "ReactorRulesRecipes.FluxMapNotNullOrElseRecipe",
            "ReactorRulesRecipes.FluxMapNotNullTransformationOrElseRecipe",
            "ReactorRulesRecipes.FluxOfTypeRecipe",
            "ReactorRulesRecipes.FluxOnErrorCompleteRecipe",
            "ReactorRulesRecipes.FluxOnErrorCompleteClassRecipe",
            "ReactorRulesRecipes.FluxOnErrorCompletePredicateRecipe",
            "ReactorRulesRecipes.FluxOnErrorContinueRecipe",
            "ReactorRulesRecipes.FluxOnErrorMapRecipe",
            "ReactorRulesRecipes.FluxOnErrorResumeRecipe",
            "ReactorRulesRecipes.FluxOnErrorReturnRecipe",
            "ReactorRulesRecipes.FluxSortRecipe",
            "ReactorRulesRecipes.FluxSwitchIfEmptyOfEmptyPublisherRecipe",
            "ReactorRulesRecipes.FluxTakeRecipe",
            "ReactorRulesRecipes.FluxTakeWhileRecipe",
            "ReactorRulesRecipes.FluxThenRecipe",
            "ReactorRulesRecipes.FluxThenEmptyRecipe",
            "ReactorRulesRecipes.FluxThenManyRecipe",
            "ReactorRulesRecipes.FluxThenMonoRecipe",
            "ReactorRulesRecipes.FluxTransformMaxRecipe",
            "ReactorRulesRecipes.FluxTransformMaxWithComparatorRecipe",
            "ReactorRulesRecipes.FluxTransformMinRecipe",
            "ReactorRulesRecipes.FluxTransformMinWithComparatorRecipe",
            "ReactorRulesRecipes.FluxZipRecipe",
            "ReactorRulesRecipes.FluxZipWithCombinatorRecipe",
            "ReactorRulesRecipes.FluxZipWithIterableRecipe",
            "ReactorRulesRecipes.FluxZipWithIterableBiFunctionRecipe",
            "ReactorRulesRecipes.FluxZipWithIterableMapFunctionRecipe",
            "ReactorRulesRecipes.MathFluxMaxRecipe",
            "ReactorRulesRecipes.MathFluxMinRecipe",
            "ReactorRulesRecipes.MonoCastRecipe",
            "ReactorRulesRecipes.MonoDefaultIfEmptyRecipe",
            "ReactorRulesRecipes.MonoDeferMonoJustOrEmptyRecipe",
            "ReactorRulesRecipes.MonoDeferredErrorRecipe",
            "ReactorRulesRecipes.MonoDoOnErrorRecipe",
            "ReactorRulesRecipes.MonoEmptyRecipe",
            "ReactorRulesRecipes.MonoErrorSupplierRecipe",
            "ReactorRulesRecipes.MonoFlatMapRecipe",
            "ReactorRulesRecipes.MonoFlatMapIterableRecipe",
            "ReactorRulesRecipes.MonoFlatMapIterableIdentityRecipe",
            "ReactorRulesRecipes.MonoFlatMapManyRecipe",
            "ReactorRulesRecipes.MonoFlatMapToFluxRecipe",
            "ReactorRulesRecipes.MonoFluxRecipe",
            "ReactorRulesRecipes.MonoFromFutureAsyncLoadingCacheGetRecipe",
            "ReactorRulesRecipes.MonoFromFutureAsyncLoadingCacheGetAllRecipe",
            "ReactorRulesRecipes.MonoFromFutureSupplierRecipe",
            "ReactorRulesRecipes.MonoFromFutureSupplierBooleanRecipe",
            "ReactorRulesRecipes.MonoFromOptionalSwitchIfEmptyRecipe",
            "ReactorRulesRecipes.MonoFromSupplierRecipe",
            "ReactorRulesRecipes.MonoIdentityRecipe",
            "ReactorRulesRecipes.MonoJustRecipe",
            "ReactorRulesRecipes.MonoJustOrEmptyObjectRecipe",
            "ReactorRulesRecipes.MonoJustOrEmptyOptionalRecipe",
            "ReactorRulesRecipes.MonoMapRecipe",
            "ReactorRulesRecipes.MonoMapNotNullRecipe",
            "ReactorRulesRecipes.MonoOfTypeRecipe",
            "ReactorRulesRecipes.MonoOnErrorCompleteRecipe",
            "ReactorRulesRecipes.MonoOnErrorCompleteClassRecipe",
            "ReactorRulesRecipes.MonoOnErrorCompletePredicateRecipe",
            "ReactorRulesRecipes.MonoOnErrorContinueRecipe",
            "ReactorRulesRecipes.MonoOnErrorMapRecipe",
            "ReactorRulesRecipes.MonoOnErrorResumeRecipe",
            "ReactorRulesRecipes.MonoOnErrorReturnRecipe",
            "ReactorRulesRecipes.MonoSingleRecipe",
            "ReactorRulesRecipes.MonoSingleOptionalRecipe",
            "ReactorRulesRecipes.MonoThenRecipe",
            "ReactorRulesRecipes.MonoThenEmptyRecipe",
            "ReactorRulesRecipes.MonoThenManyRecipe",
            "ReactorRulesRecipes.MonoThenMonoRecipe",
            "ReactorRulesRecipes.MonoThenMonoFluxRecipe",
            "ReactorRulesRecipes.MonoThenReturnRecipe",
            "ReactorRulesRecipes.MonoZipRecipe",
            "ReactorRulesRecipes.MonoZipWithCombinatorRecipe",
            "ReactorRulesRecipes.OptionalMapMonoJustRecipe",
            "ReactorRulesRecipes.PublisherProbeAssertWasCancelledRecipe",
            "ReactorRulesRecipes.PublisherProbeAssertWasNotCancelledRecipe",
            "ReactorRulesRecipes.PublisherProbeAssertWasNotRequestedRecipe",
            "ReactorRulesRecipes.PublisherProbeAssertWasNotSubscribedRecipe",
            "ReactorRulesRecipes.PublisherProbeAssertWasRequestedRecipe",
            "ReactorRulesRecipes.PublisherProbeAssertWasSubscribedRecipe",
            "ReactorRulesRecipes.PublisherProbeEmptyRecipe",
            "ReactorRulesRecipes.StepVerifierFromFluxRecipe",
            "ReactorRulesRecipes.StepVerifierFromMonoRecipe",
            "ReactorRulesRecipes.StepVerifierLastStepVerifyCompleteRecipe",
            "ReactorRulesRecipes.StepVerifierLastStepVerifyErrorRecipe",
            "ReactorRulesRecipes.StepVerifierLastStepVerifyErrorClassRecipe",
            "ReactorRulesRecipes.StepVerifierLastStepVerifyErrorMatchesRecipe",
            "ReactorRulesRecipes.StepVerifierLastStepVerifyErrorMessageRecipe",
            "ReactorRulesRecipes.StepVerifierLastStepVerifyErrorSatisfiesRecipe",
            "ReactorRulesRecipes.StepVerifierLastStepVerifyErrorSatisfiesAssertJRecipe",
            "ReactorRulesRecipes.StepVerifierLastStepVerifyTimeoutRecipe",
            "ReactorRulesRecipes.StepVerifierStepExpectNextRecipe",
            "ReactorRulesRecipes.StepVerifierStepIdentityRecipe",
            "ReactorRulesRecipes.StepVerifierVerifyRecipe",
            "ReactorRulesRecipes.StepVerifierVerifyDurationRecipe",
            "ReactorRulesRecipes.StepVerifierVerifyLaterRecipe",
            "ImmutableTableRulesRecipes.CellToImmutableTableRecipe",
            "ImmutableTableRulesRecipes.ImmutableTableBuilderRecipe",
            "ImmutableTableRulesRecipes.ImmutableTableBuilderBuildOrThrowRecipe",
            "ImmutableTableRulesRecipes.ImmutableTableOfRecipe",
            "ImmutableTableRulesRecipes.StreamOfCellsToImmutableTableRecipe",
            "ImmutableSetMultimapRulesRecipes.EmptyImmutableSetMultimapRecipe",
            "ImmutableSetMultimapRulesRecipes.EntryToImmutableSetMultimapRecipe",
            "ImmutableSetMultimapRulesRecipes.ImmutableSetMultimapBuilderRecipe",
            "ImmutableSetMultimapRulesRecipes.IterableToImmutableSetMultimapRecipe",
            "ImmutableSetMultimapRulesRecipes.PairToImmutableSetMultimapRecipe",
            "ImmutableSetMultimapRulesRecipes.StreamOfMapEntriesToImmutableSetMultimapRecipe",
            "ImmutableSetMultimapRulesRecipes.TransformMultimapValuesToImmutableSetMultimapRecipe",
            "ImmutableSetMultimapRulesRecipes.TransformMultimapValuesToImmutableSetMultimap2Recipe",
            "AssertJEnumerableRulesRecipes.EnumerableAssertHasSameSizeAsRecipe",
            "AssertJEnumerableRulesRecipes.EnumerableAssertHasSizeRecipe",
            "AssertJEnumerableRulesRecipes.EnumerableAssertHasSizeBetweenRecipe",
            "AssertJEnumerableRulesRecipes.EnumerableAssertHasSizeGreaterThanRecipe",
            "AssertJEnumerableRulesRecipes.EnumerableAssertHasSizeGreaterThanOrEqualToRecipe",
            "AssertJEnumerableRulesRecipes.EnumerableAssertHasSizeLessThanRecipe",
            "AssertJEnumerableRulesRecipes.EnumerableAssertHasSizeLessThanOrEqualToRecipe",
            "AssertJEnumerableRulesRecipes.EnumerableAssertIsEmptyRecipe",
            "AssertJEnumerableRulesRecipes.EnumerableAssertIsNotEmptyRecipe",
            "ComparatorRulesRecipes.CollectionsMaxRecipe",
            "ComparatorRulesRecipes.CollectionsMaxWithComparatorRecipe",
            "ComparatorRulesRecipes.CollectionsMinRecipe",
            "ComparatorRulesRecipes.CollectionsMinWithComparatorRecipe",
            "ComparatorRulesRecipes.CollectionsSortRecipe",
            "ComparatorRulesRecipes.ComparatorsMaxRecipe",
            "ComparatorRulesRecipes.ComparatorsMinRecipe",
            "ComparatorRulesRecipes.CompareToRecipe",
            "ComparatorRulesRecipes.ComparingEnumRecipe",
            "ComparatorRulesRecipes.CustomComparatorRecipe",
            "ComparatorRulesRecipes.IsLessThanRecipe",
            "ComparatorRulesRecipes.IsLessThanOrEqualToRecipe",
            "ComparatorRulesRecipes.MaxByNaturalOrderRecipe",
            "ComparatorRulesRecipes.MaxOfArrayRecipe",
            "ComparatorRulesRecipes.MaxOfPairCustomOrderRecipe",
            "ComparatorRulesRecipes.MaxOfPairNaturalOrderRecipe",
            "ComparatorRulesRecipes.MaxOfVarargsRecipe",
            "ComparatorRulesRecipes.MinByNaturalOrderRecipe",
            "ComparatorRulesRecipes.MinOfArrayRecipe",
            "ComparatorRulesRecipes.MinOfPairCustomOrderRecipe",
            "ComparatorRulesRecipes.MinOfPairNaturalOrderRecipe",
            "ComparatorRulesRecipes.MinOfVarargsRecipe",
            "ComparatorRulesRecipes.NaturalOrderRecipe",
            "ComparatorRulesRecipes.ReverseOrderRecipe",
            "ComparatorRulesRecipes.ThenComparingRecipe",
            "ComparatorRulesRecipes.ThenComparingCustomRecipe",
            "ComparatorRulesRecipes.ThenComparingCustomReversedRecipe",
            "ComparatorRulesRecipes.ThenComparingDoubleRecipe",
            "ComparatorRulesRecipes.ThenComparingIntRecipe",
            "ComparatorRulesRecipes.ThenComparingLongRecipe",
            "ComparatorRulesRecipes.ThenComparingNaturalOrderRecipe",
            "ComparatorRulesRecipes.ThenComparingReversedRecipe",
            "PatternRulesRecipes.PatternAsPredicateRecipe",
            "PatternRulesRecipes.PatternCompileAsPredicateRecipe",
            "ImmutableMapRulesRecipes.EntryIterableToImmutableMapRecipe",
            "ImmutableMapRulesRecipes.EntryToImmutableMapRecipe",
            "ImmutableMapRulesRecipes.ImmutableMapBuilderRecipe",
            "ImmutableMapRulesRecipes.ImmutableMapBuilderBuildOrThrowRecipe",
            "ImmutableMapRulesRecipes.ImmutableMapCopyOfMapsFilterKeysRecipe",
            "ImmutableMapRulesRecipes.ImmutableMapCopyOfMapsFilterValuesRecipe",
            "ImmutableMapRulesRecipes.ImmutableMapOfRecipe",
            "ImmutableMapRulesRecipes.ImmutableMapOf1Recipe",
            "ImmutableMapRulesRecipes.ImmutableMapOf2Recipe",
            "ImmutableMapRulesRecipes.ImmutableMapOf3Recipe",
            "ImmutableMapRulesRecipes.ImmutableMapOf4Recipe",
            "ImmutableMapRulesRecipes.ImmutableMapOf5Recipe",
            "ImmutableMapRulesRecipes.ImmutableMapOfEntriesRecipe",
            "ImmutableMapRulesRecipes.IndexIterableToImmutableMapRecipe",
            "ImmutableMapRulesRecipes.IterableToImmutableMapRecipe",
            "ImmutableMapRulesRecipes.StreamOfMapEntriesToImmutableMapRecipe",
            "ImmutableMapRulesRecipes.TransformMapValuesToImmutableMapRecipe",
            "AssertJCharSequenceRulesRecipes.AssertThatCharSequenceHasSizeRecipe",
            "AssertJCharSequenceRulesRecipes.AssertThatCharSequenceIsEmptyRecipe",
            "AssertJCharSequenceRulesRecipes.AssertThatCharSequenceIsNotEmptyRecipe",
            "EqualityRulesRecipes.DoubleNegationRecipe",
            "EqualityRulesRecipes.EnumReferenceEqualityRecipe",
            "EqualityRulesRecipes.EnumReferenceEqualityLambdaRecipe",
            "EqualityRulesRecipes.EqualsRecipe",
            "EqualityRulesRecipes.EqualsPredicateRecipe",
            "EqualityRulesRecipes.IndirectDoubleNegationRecipe",
            "EqualityRulesRecipes.NegationRecipe",
            "EqualityRulesRecipes.ObjectsEqualsRecipe",
            "EqualityRulesRecipes.PredicateLambdaRecipe",
            "ImmutableMultisetRulesRecipes.EmptyImmutableMultisetRecipe",
            "ImmutableMultisetRulesRecipes.ImmutableMultisetBuilderRecipe",
            "ImmutableMultisetRulesRecipes.IterableToImmutableMultisetRecipe",
            "ImmutableMultisetRulesRecipes.StreamToImmutableMultisetRecipe",
            "AssertJIterableRulesRecipes.AssertThatIterableHasOneElementEqualToRecipe",
            "AssertJIterableRulesRecipes.AssertThatIterableIsEmptyRecipe",
            "AssertJIterableRulesRecipes.AssertThatIterableIsNotEmptyRecipe",
            "AssertJIterableRulesRecipes.AssertThatIterableSizeRecipe",
            "InputStreamRulesRecipes.InputStreamReadAllBytesRecipe",
            "InputStreamRulesRecipes.InputStreamReadNBytesRecipe",
            "InputStreamRulesRecipes.InputStreamSkipNBytesRecipe",
            "InputStreamRulesRecipes.InputStreamTransferToRecipe",
            "ClassRulesRecipes.ClassIsInstanceRecipe",
            "ClassRulesRecipes.ClassLiteralIsInstancePredicateRecipe",
            "ClassRulesRecipes.ClassReferenceCastRecipe",
            "ClassRulesRecipes.ClassReferenceIsInstancePredicateRecipe",
            "ClassRulesRecipes.InstanceofRecipe",
            "MockitoRulesRecipes.InvocationOnMockGetArgumentsRecipe",
            "MockitoRulesRecipes.InvocationOnMockGetArgumentsWithTypeParameterRecipe",
            "MockitoRulesRecipes.NeverRecipe",
            "MockitoRulesRecipes.VerifyOnceRecipe",
            "IntStreamRulesRecipes.ConcatOneIntStreamRecipe",
            "IntStreamRulesRecipes.ConcatTwoIntStreamsRecipe",
            "IntStreamRulesRecipes.FilterOuterIntStreamAfterFlatMapRecipe",
            "IntStreamRulesRecipes.FilterOuterStreamAfterFlatMapToIntRecipe",
            "IntStreamRulesRecipes.FlatMapOuterIntStreamAfterFlatMapRecipe",
            "IntStreamRulesRecipes.FlatMapOuterStreamAfterFlatMapToIntRecipe",
            "IntStreamRulesRecipes.IntStreamAllMatchRecipe",
            "IntStreamRulesRecipes.IntStreamAllMatch2Recipe",
            "IntStreamRulesRecipes.IntStreamAnyMatchRecipe",
            "IntStreamRulesRecipes.IntStreamClosedOpenRangeRecipe",
            "IntStreamRulesRecipes.IntStreamFilterSortedRecipe",
            "IntStreamRulesRecipes.IntStreamIsEmptyRecipe",
            "IntStreamRulesRecipes.IntStreamIsNotEmptyRecipe",
            "IntStreamRulesRecipes.IntStreamMinRecipe",
            "IntStreamRulesRecipes.IntStreamNoneMatchRecipe",
            "IntStreamRulesRecipes.IntStreamNoneMatch2Recipe",
            "IntStreamRulesRecipes.IntStreamTakeWhileRecipe",
            "IntStreamRulesRecipes.MapOuterIntStreamAfterFlatMapRecipe",
            "IntStreamRulesRecipes.MapOuterStreamAfterFlatMapToIntRecipe",
            "ImmutableSetRulesRecipes.ImmutableSetBuilderRecipe",
            "ImmutableSetRulesRecipes.ImmutableSetCopyOfSetViewRecipe",
            "ImmutableSetRulesRecipes.ImmutableSetOfRecipe",
            "ImmutableSetRulesRecipes.ImmutableSetOf1Recipe",
            "ImmutableSetRulesRecipes.ImmutableSetOf2Recipe",
            "ImmutableSetRulesRecipes.ImmutableSetOf3Recipe",
            "ImmutableSetRulesRecipes.ImmutableSetOf4Recipe",
            "ImmutableSetRulesRecipes.ImmutableSetOf5Recipe",
            "ImmutableSetRulesRecipes.IterableToImmutableSetRecipe",
            "ImmutableSetRulesRecipes.SetsDifferenceRecipe",
            "ImmutableSetRulesRecipes.SetsDifferenceMapRecipe",
            "ImmutableSetRulesRecipes.SetsDifferenceMultimapRecipe",
            "ImmutableSetRulesRecipes.SetsIntersectionRecipe",
            "ImmutableSetRulesRecipes.SetsIntersectionMapRecipe",
            "ImmutableSetRulesRecipes.SetsIntersectionMultimapRecipe",
            "ImmutableSetRulesRecipes.SetsUnionRecipe",
            "ImmutableSetRulesRecipes.StreamToImmutableSetRecipe",
            "DoubleStreamRulesRecipes.ConcatOneDoubleStreamRecipe",
            "DoubleStreamRulesRecipes.ConcatTwoDoubleStreamsRecipe",
            "DoubleStreamRulesRecipes.DoubleStreamAllMatchRecipe",
            "DoubleStreamRulesRecipes.DoubleStreamAllMatch2Recipe",
            "DoubleStreamRulesRecipes.DoubleStreamAnyMatchRecipe",
            "DoubleStreamRulesRecipes.DoubleStreamFilterSortedRecipe",
            "DoubleStreamRulesRecipes.DoubleStreamIsEmptyRecipe",
            "DoubleStreamRulesRecipes.DoubleStreamIsNotEmptyRecipe",
            "DoubleStreamRulesRecipes.DoubleStreamMinRecipe",
            "DoubleStreamRulesRecipes.DoubleStreamNoneMatchRecipe",
            "DoubleStreamRulesRecipes.DoubleStreamNoneMatch2Recipe",
            "DoubleStreamRulesRecipes.DoubleStreamTakeWhileRecipe",
            "DoubleStreamRulesRecipes.FilterOuterDoubleStreamAfterFlatMapRecipe",
            "DoubleStreamRulesRecipes.FilterOuterStreamAfterFlatMapToDoubleRecipe",
            "DoubleStreamRulesRecipes.FlatMapOuterDoubleStreamAfterFlatMapRecipe",
            "DoubleStreamRulesRecipes.FlatMapOuterStreamAfterFlatMapToDoubleRecipe",
            "DoubleStreamRulesRecipes.MapOuterDoubleStreamAfterFlatMapRecipe",
            "DoubleStreamRulesRecipes.MapOuterStreamAfterFlatMapToDoubleRecipe",
            "AssertJStringRulesRecipes.AbstractStringAssertStringIsEmptyRecipe",
            "AssertJStringRulesRecipes.AbstractStringAssertStringIsNotEmptyRecipe",
            "AssertJStringRulesRecipes.AssertThatDoesNotMatchRecipe",
            "AssertJStringRulesRecipes.AssertThatMatchesRecipe",
            "AssertJStringRulesRecipes.AssertThatPathContentRecipe",
            "AssertJStringRulesRecipes.AssertThatPathContentUtf8Recipe",
            "AssertJStringRulesRecipes.AssertThatStringContainsRecipe",
            "AssertJStringRulesRecipes.AssertThatStringDoesNotContainRecipe",
            "AssertJThrowingCallableRulesRecipes.AbstractThrowableAssertHasMessageRecipe",
            "AssertJThrowingCallableRulesRecipes.AbstractThrowableAssertWithFailMessageRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByAsInstanceOfThrowableRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByHasMessageRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByHasMessageContainingRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByHasMessageNotContainingRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByHasMessageParametersRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByHasMessageStartingWithRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIOExceptionRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIOExceptionHasMessageRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIOExceptionHasMessageContainingRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIOExceptionHasMessageNotContainingRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIOExceptionHasMessageParametersRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIOExceptionHasMessageStartingWithRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIOExceptionRootCauseHasMessageRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIllegalArgumentExceptionRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIllegalArgumentExceptionHasMessageRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIllegalArgumentExceptionHasMessageContainingRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIllegalArgumentExceptionHasMessageNotContainingAnyRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIllegalArgumentExceptionHasMessageParametersRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIllegalArgumentExceptionHasMessageStartingWithRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIllegalArgumentExceptionRootCauseHasMessageRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIllegalStateExceptionRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIllegalStateExceptionHasMessageRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIllegalStateExceptionHasMessageContainingRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIllegalStateExceptionHasMessageNotContainingRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIllegalStateExceptionHasMessageParametersRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIllegalStateExceptionHasMessageStartingWithRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIllegalStateExceptionRootCauseHasMessageRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByIsInstanceOfRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByNullPointerExceptionRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByNullPointerExceptionHasMessageRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByNullPointerExceptionHasMessageContainingRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByNullPointerExceptionHasMessageNotContainingRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByNullPointerExceptionHasMessageParametersRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByNullPointerExceptionHasMessageStartingWithRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByNullPointerExceptionRootCauseHasMessageRecipe",
            "AssertJThrowingCallableRulesRecipes.AssertThatThrownByRootCauseHasMessageRecipe",
            "MapEntryRulesRecipes.MapEntryRecipe",
            "MapEntryRulesRecipes.MapEntryComparingByKeyRecipe",
            "MapEntryRulesRecipes.MapEntryComparingByKeyWithCustomComparatorRecipe",
            "MapEntryRulesRecipes.MapEntryComparingByValueRecipe",
            "MapEntryRulesRecipes.MapEntryComparingByValueWithCustomComparatorRecipe",
            "ImmutableSortedMultisetRulesRecipes.EmptyImmutableSortedMultisetRecipe",
            "ImmutableSortedMultisetRulesRecipes.ImmutableSortedMultisetBuilderRecipe",
            "ImmutableSortedMultisetRulesRecipes.ImmutableSortedMultisetNaturalOrderBuilderRecipe",
            "ImmutableSortedMultisetRulesRecipes.ImmutableSortedMultisetReverseOrderBuilderRecipe",
            "ImmutableSortedMultisetRulesRecipes.IterableToImmutableSortedMultisetRecipe",
            "ImmutableSortedMultisetRulesRecipes.StreamToImmutableSortedMultisetRecipe",
            "AssertJIntegerRulesRecipes.AbstractIntegerAssertIsEqualToRecipe",
            "AssertJIntegerRulesRecipes.AbstractIntegerAssertIsNotEqualToRecipe",
            "AssertJIntegerRulesRecipes.AbstractIntegerAssertIsNotZeroRecipe",
            "AssertJIntegerRulesRecipes.AbstractIntegerAssertIsOneRecipe",
            "AssertJIntegerRulesRecipes.AbstractIntegerAssertIsZeroRecipe",
            "AssertJMapRulesRecipes.AbstractMapAssertContainsExactlyEntriesOfRecipe",
            "AssertJMapRulesRecipes.AbstractMapAssertContainsExactlyInAnyOrderEntriesOfRecipe",
            "AssertJMapRulesRecipes.AbstractMapAssertHasSameSizeAsRecipe",
            "AssertJMapRulesRecipes.AbstractMapAssertIsEmptyRecipe",
            "AssertJMapRulesRecipes.AbstractMapAssertIsNotEmptyRecipe",
            "AssertJMapRulesRecipes.AssertThatMapContainsEntryRecipe",
            "AssertJMapRulesRecipes.AssertThatMapContainsKeyRecipe",
            "AssertJMapRulesRecipes.AssertThatMapContainsOnlyKeysRecipe",
            "AssertJMapRulesRecipes.AssertThatMapContainsValueRecipe",
            "AssertJMapRulesRecipes.AssertThatMapDoesNotContainKeyRecipe",
            "AssertJMapRulesRecipes.AssertThatMapDoesNotContainValueRecipe",
            "AssertJMapRulesRecipes.AssertThatMapHasSizeRecipe",
            "AssertJMapRulesRecipes.AssertThatMapIsEmptyRecipe",
            "AssertJMapRulesRecipes.AssertThatMapIsNotEmptyRecipe",
            "OptionalRulesRecipes.FilterOuterOptionalAfterFlatMapRecipe",
            "OptionalRulesRecipes.FlatMapOuterOptionalAfterFlatMapRecipe",
            "OptionalRulesRecipes.FlatMapToOptionalRecipe",
            "OptionalRulesRecipes.MapOptionalToBooleanRecipe",
            "OptionalRulesRecipes.MapOuterOptionalAfterFlatMapRecipe",
            "OptionalRulesRecipes.MapToNullableRecipe",
            "OptionalRulesRecipes.OptionalEmptyRecipe",
            "OptionalRulesRecipes.OptionalEqualsOptionalRecipe",
            "OptionalRulesRecipes.OptionalFilterRecipe",
            "OptionalRulesRecipes.OptionalFirstIteratorElementRecipe",
            "OptionalRulesRecipes.OptionalIdentityRecipe",
            "OptionalRulesRecipes.OptionalIsEmptyRecipe",
            "OptionalRulesRecipes.OptionalIsPresentRecipe",
            "OptionalRulesRecipes.OptionalMapRecipe",
            "OptionalRulesRecipes.OptionalOfNullableRecipe",
            "OptionalRulesRecipes.OptionalOrElseRecipe",
            "OptionalRulesRecipes.OptionalOrElseThrowRecipe",
            "OptionalRulesRecipes.OptionalOrElseThrowMethodReferenceRecipe",
            "OptionalRulesRecipes.OptionalOrOtherOptionalRecipe",
            "OptionalRulesRecipes.OptionalStreamRecipe",
            "OptionalRulesRecipes.OrOrElseThrowRecipe",
            "OptionalRulesRecipes.StreamFlatMapOptionalRecipe",
            "OptionalRulesRecipes.StreamMapToOptionalGetRecipe",
            "OptionalRulesRecipes.TernaryOperatorOptionalNegativeFilteringRecipe",
            "OptionalRulesRecipes.TernaryOperatorOptionalPositiveFilteringRecipe",
            "ImmutableEnumSetRulesRecipes.SetsImmutableEnumSet1Recipe",
            "ImmutableEnumSetRulesRecipes.SetsImmutableEnumSet2Recipe",
            "ImmutableEnumSetRulesRecipes.SetsImmutableEnumSet3Recipe",
            "ImmutableEnumSetRulesRecipes.SetsImmutableEnumSet4Recipe",
            "ImmutableEnumSetRulesRecipes.SetsImmutableEnumSet5Recipe",
            "ImmutableEnumSetRulesRecipes.SetsImmutableEnumSet6Recipe",
            "ImmutableEnumSetRulesRecipes.SetsImmutableEnumSetArraysAsListRecipe",
            "ImmutableEnumSetRulesRecipes.SetsImmutableEnumSetIterableRecipe",
            "ImmutableEnumSetRulesRecipes.SetsImmutableEnumSetVarArgsRecipe",
            "ImmutableEnumSetRulesRecipes.StreamToImmutableEnumSetRecipe",
            "CollectionRulesRecipes.ArraysAsListRecipe",
            "CollectionRulesRecipes.CollectionAddAllToCollectionBlockRecipe",
            "CollectionRulesRecipes.CollectionAddAllToCollectionExpressionRecipe",
            "CollectionRulesRecipes.CollectionContainsRecipe",
            "CollectionRulesRecipes.CollectionForEachRecipe",
            "CollectionRulesRecipes.CollectionIsEmptyRecipe",
            "CollectionRulesRecipes.CollectionIteratorRecipe",
            "CollectionRulesRecipes.CollectionRemoveAllFromCollectionBlockRecipe",
            "CollectionRulesRecipes.CollectionRemoveAllFromCollectionExpressionRecipe",
            "CollectionRulesRecipes.CollectionSizeRecipe",
            "CollectionRulesRecipes.CollectionToArrayRecipe",
            "CollectionRulesRecipes.ImmutableCollectionAsListRecipe",
            "CollectionRulesRecipes.ImmutableCollectionContainsRecipe",
            "CollectionRulesRecipes.ImmutableCollectionParallelStreamRecipe",
            "CollectionRulesRecipes.ImmutableCollectionStreamRecipe",
            "CollectionRulesRecipes.ImmutableCollectionToArrayWithArrayRecipe",
            "CollectionRulesRecipes.ImmutableCollectionToArrayWithGeneratorRecipe",
            "CollectionRulesRecipes.ImmutableCollectionToStringRecipe",
            "CollectionRulesRecipes.NewArrayListFromCollectionRecipe",
            "CollectionRulesRecipes.OptionalFirstCollectionElementRecipe",
            "CollectionRulesRecipes.OptionalFirstQueueElementRecipe",
            "CollectionRulesRecipes.RemoveOptionalFirstNavigableSetElementRecipe",
            "CollectionRulesRecipes.RemoveOptionalFirstQueueElementRecipe",
            "CollectionRulesRecipes.SetStreamRecipe",
            "MapRulesRecipes.CreateEnumMapRecipe",
            "MapRulesRecipes.MapContainsKeyRecipe",
            "MapRulesRecipes.MapContainsValueRecipe",
            "MapRulesRecipes.MapGetOrDefaultRecipe",
            "MapRulesRecipes.MapGetOrNullRecipe",
            "MapRulesRecipes.MapIsEmptyRecipe",
            "MapRulesRecipes.MapKeyStreamRecipe",
            "MapRulesRecipes.MapSizeRecipe",
            "MapRulesRecipes.MapValueStreamRecipe",
            "AssertJObjectRulesRecipes.AssertThatHasToStringRecipe",
            "AssertJObjectRulesRecipes.AssertThatIsInstanceOfRecipe",
            "AssertJObjectRulesRecipes.AssertThatIsIsEqualToRecipe",
            "AssertJObjectRulesRecipes.AssertThatIsIsNotEqualToRecipe",
            "AssertJObjectRulesRecipes.AssertThatIsNotInstanceOfRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatBooleanArrayContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatBooleanArrayWithFailMessageContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatBooleanArrayWithFailMessageSupplierContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatByteArrayContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatByteArrayWithFailMessageContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatByteArrayWithFailMessageSupplierContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatCharArrayContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatCharArrayWithFailMessageContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatCharArrayWithFailMessageSupplierContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatCodeDoesNotThrowAnyExceptionRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatCodeWithFailMessageStringDoesNotThrowAnyExceptionRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatCodeWithFailMessageSupplierDoesNotThrowAnyExceptionRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatDoubleArrayContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatDoubleArrayContainsExactlyWithOffsetRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatDoubleArrayWithFailMessageContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatDoubleArrayWithFailMessageContainsExactlyWithOffsetRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatDoubleArrayWithFailMessageSupplierContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatDoubleArrayWithFailMessageSupplierContainsExactlyWithOffsetRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatFloatArrayContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatFloatArrayContainsExactlyWithOffsetRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatFloatArrayWithFailMessageContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatFloatArrayWithFailMessageContainsExactlyWithOffsetRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatFloatArrayWithFailMessageSupplierContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatFloatArrayWithFailMessageSupplierContainsExactlyWithOffsetRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatIntArrayContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatIntArrayWithFailMessageContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatIntArrayWithFailMessageSupplierContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatIsFalseRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatIsInstanceOfRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatIsNotNullRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatIsNotSameAsRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatIsNullRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatIsSameAsRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatIsTrueRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatLongArrayContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatLongArrayWithFailMessageContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatLongArrayWithFailMessageSupplierContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatObjectArrayContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatObjectArrayWithFailMessageContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatObjectArrayWithFailMessageSupplierContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatShortArrayContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatShortArrayWithFailMessageContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatShortArrayWithFailMessageSupplierContainsExactlyRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatThrownByIsExactlyInstanceOfRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatThrownByIsInstanceOfRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatThrownByWithFailMessageStringIsExactlyInstanceOfRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatThrownByWithFailMessageStringIsInstanceOfRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatThrownByWithFailMessageSupplierIsExactlyInstanceOfRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatThrownByWithFailMessageSupplierIsInstanceOfRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatWithFailMessageStringIsFalseRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatWithFailMessageStringIsInstanceOfRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatWithFailMessageStringIsNotNullRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatWithFailMessageStringIsNotSameAsRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatWithFailMessageStringIsNullRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatWithFailMessageStringIsSameAsRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatWithFailMessageStringIsTrueRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatWithFailMessageSupplierIsFalseRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatWithFailMessageSupplierIsInstanceOfRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatWithFailMessageSupplierIsNotNullRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatWithFailMessageSupplierIsNotSameAsRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatWithFailMessageSupplierIsNullRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatWithFailMessageSupplierIsSameAsRecipe",
            "JUnitToAssertJRulesRecipes.AssertThatWithFailMessageSupplierIsTrueRecipe",
            "JUnitToAssertJRulesRecipes.FailRecipe",
            "JUnitToAssertJRulesRecipes.FailWithMessageRecipe",
            "JUnitToAssertJRulesRecipes.FailWithMessageAndThrowableRecipe",
            "JUnitToAssertJRulesRecipes.FailWithThrowableRecipe",
            "AssertJDoubleRulesRecipes.AbstractDoubleAssertIsCloseToWithOffsetRecipe",
            "AssertJDoubleRulesRecipes.AbstractDoubleAssertIsEqualToRecipe",
            "AssertJDoubleRulesRecipes.AbstractDoubleAssertIsNotEqualToRecipe",
            "AssertJDoubleRulesRecipes.AbstractDoubleAssertIsNotZeroRecipe",
            "AssertJDoubleRulesRecipes.AbstractDoubleAssertIsOneRecipe",
            "AssertJDoubleRulesRecipes.AbstractDoubleAssertIsZeroRecipe",
            "LongStreamRulesRecipes.ConcatOneLongStreamRecipe",
            "LongStreamRulesRecipes.ConcatTwoLongStreamsRecipe",
            "LongStreamRulesRecipes.FilterOuterLongStreamAfterFlatMapRecipe",
            "LongStreamRulesRecipes.FilterOuterStreamAfterFlatMapToLongRecipe",
            "LongStreamRulesRecipes.FlatMapOuterLongStreamAfterFlatMapRecipe",
            "LongStreamRulesRecipes.FlatMapOuterStreamAfterFlatMapToLongRecipe",
            "LongStreamRulesRecipes.LongStreamAllMatchRecipe",
            "LongStreamRulesRecipes.LongStreamAllMatch2Recipe",
            "LongStreamRulesRecipes.LongStreamAnyMatchRecipe",
            "LongStreamRulesRecipes.LongStreamClosedOpenRangeRecipe",
            "LongStreamRulesRecipes.LongStreamFilterSortedRecipe",
            "LongStreamRulesRecipes.LongStreamIsEmptyRecipe",
            "LongStreamRulesRecipes.LongStreamIsNotEmptyRecipe",
            "LongStreamRulesRecipes.LongStreamMinRecipe",
            "LongStreamRulesRecipes.LongStreamNoneMatchRecipe",
            "LongStreamRulesRecipes.LongStreamNoneMatch2Recipe",
            "LongStreamRulesRecipes.LongStreamTakeWhileRecipe",
            "LongStreamRulesRecipes.MapOuterLongStreamAfterFlatMapRecipe",
            "LongStreamRulesRecipes.MapOuterStreamAfterFlatMapToLongRecipe",
            "AssertJLongRulesRecipes.AbstractLongAssertIsEqualToRecipe",
            "AssertJLongRulesRecipes.AbstractLongAssertIsNotEqualToRecipe",
            "AssertJLongRulesRecipes.AbstractLongAssertIsNotZeroRecipe",
            "AssertJLongRulesRecipes.AbstractLongAssertIsOneRecipe",
            "AssertJLongRulesRecipes.AbstractLongAssertIsZeroRecipe",
            "AssertJByteRulesRecipes.AbstractByteAssertIsEqualToRecipe",
            "AssertJByteRulesRecipes.AbstractByteAssertIsNotEqualToRecipe",
            "AssertJByteRulesRecipes.AbstractByteAssertIsNotZeroRecipe",
            "AssertJByteRulesRecipes.AbstractByteAssertIsOneRecipe",
            "AssertJByteRulesRecipes.AbstractByteAssertIsZeroRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualArrayIterationOrderRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualArrayIterationOrderWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualArraysIrrespectiveOfOrderRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualArraysIrrespectiveOfOrderWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualDoubleArraysWithDeltaRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualDoubleArraysWithDeltaWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualDoublesWithDeltaRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualDoublesWithDeltaWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualFloatArraysWithDeltaRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualFloatArraysWithDeltaWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualFloatsWithDeltaRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualFloatsWithDeltaWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualIterableIterationOrderRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualIterableIterationOrderWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualIteratorIterationOrderRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualIteratorIterationOrderWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualSetsRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualSetsWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertEqualWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertFalseRecipe",
            "TestNGToAssertJRulesRecipes.AssertFalseWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertNotNullRecipe",
            "TestNGToAssertJRulesRecipes.AssertNotNullWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertNotSameRecipe",
            "TestNGToAssertJRulesRecipes.AssertNotSameWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertNullRecipe",
            "TestNGToAssertJRulesRecipes.AssertNullWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertSameRecipe",
            "TestNGToAssertJRulesRecipes.AssertSameWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertThrowsRecipe",
            "TestNGToAssertJRulesRecipes.AssertThrowsWithTypeRecipe",
            "TestNGToAssertJRulesRecipes.AssertTrueRecipe",
            "TestNGToAssertJRulesRecipes.AssertTrueWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertUnequalRecipe",
            "TestNGToAssertJRulesRecipes.AssertUnequalDoublesWithDeltaRecipe",
            "TestNGToAssertJRulesRecipes.AssertUnequalDoublesWithDeltaWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertUnequalFloatsWithDeltaRecipe",
            "TestNGToAssertJRulesRecipes.AssertUnequalFloatsWithDeltaWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.AssertUnequalWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.FailRecipe",
            "TestNGToAssertJRulesRecipes.FailWithMessageRecipe",
            "TestNGToAssertJRulesRecipes.FailWithMessageAndThrowableRecipe",
            "MicrometerRulesRecipes.TagsOf1Recipe",
            "MicrometerRulesRecipes.TagsOf2Recipe",
            "MicrometerRulesRecipes.TagsOf3Recipe",
            "MicrometerRulesRecipes.TagsOf4Recipe",
            "MicrometerRulesRecipes.TagsOf5Recipe",
            "TimeRulesRecipes.ChronoLocalDateIsAfterRecipe",
            "TimeRulesRecipes.ChronoLocalDateIsBeforeRecipe",
            "TimeRulesRecipes.ChronoLocalDateTimeIsAfterRecipe",
            "TimeRulesRecipes.ChronoLocalDateTimeIsBeforeRecipe",
            "TimeRulesRecipes.ChronoZonedDateTimeIsAfterRecipe",
            "TimeRulesRecipes.ChronoZonedDateTimeIsBeforeRecipe",
            "TimeRulesRecipes.ClockInstantRecipe",
            "TimeRulesRecipes.DurationBetweenInstantsRecipe",
            "TimeRulesRecipes.DurationBetweenOffsetDateTimesRecipe",
            "TimeRulesRecipes.DurationIsZeroRecipe",
            "TimeRulesRecipes.DurationOfDaysRecipe",
            "TimeRulesRecipes.DurationOfHoursRecipe",
            "TimeRulesRecipes.DurationOfMillisRecipe",
            "TimeRulesRecipes.DurationOfMinutesRecipe",
            "TimeRulesRecipes.DurationOfNanosRecipe",
            "TimeRulesRecipes.DurationOfSecondsRecipe",
            "TimeRulesRecipes.EpochInstantRecipe",
            "TimeRulesRecipes.InstantAtOffsetRecipe",
            "TimeRulesRecipes.InstantAtZoneRecipe",
            "TimeRulesRecipes.InstantIdentityRecipe",
            "TimeRulesRecipes.InstantIsAfterRecipe",
            "TimeRulesRecipes.InstantIsBeforeRecipe",
            "TimeRulesRecipes.InstantTruncatedToMillisecondsRecipe",
            "TimeRulesRecipes.InstantTruncatedToSecondsRecipe",
            "TimeRulesRecipes.LocalDateAtStartOfDayRecipe",
            "TimeRulesRecipes.LocalDateMinusDaysRecipe",
            "TimeRulesRecipes.LocalDateMinusMonthsRecipe",
            "TimeRulesRecipes.LocalDateMinusWeeksRecipe",
            "TimeRulesRecipes.LocalDateMinusYearsRecipe",
            "TimeRulesRecipes.LocalDateOfInstantRecipe",
            "TimeRulesRecipes.LocalDatePlusDaysRecipe",
            "TimeRulesRecipes.LocalDatePlusMonthsRecipe",
            "TimeRulesRecipes.LocalDatePlusWeeksRecipe",
            "TimeRulesRecipes.LocalDatePlusYearsRecipe",
            "TimeRulesRecipes.LocalDateTimeMinusDaysRecipe",
            "TimeRulesRecipes.LocalDateTimeMinusHoursRecipe",
            "TimeRulesRecipes.LocalDateTimeMinusMinutesRecipe",
            "TimeRulesRecipes.LocalDateTimeMinusMonthsRecipe",
            "TimeRulesRecipes.LocalDateTimeMinusNanosRecipe",
            "TimeRulesRecipes.LocalDateTimeMinusSecondsRecipe",
            "TimeRulesRecipes.LocalDateTimeMinusWeeksRecipe",
            "TimeRulesRecipes.LocalDateTimeMinusYearsRecipe",
            "TimeRulesRecipes.LocalDateTimeOfInstantRecipe",
            "TimeRulesRecipes.LocalDateTimePlusDaysRecipe",
            "TimeRulesRecipes.LocalDateTimePlusHoursRecipe",
            "TimeRulesRecipes.LocalDateTimePlusMinutesRecipe",
            "TimeRulesRecipes.LocalDateTimePlusMonthsRecipe",
            "TimeRulesRecipes.LocalDateTimePlusNanosRecipe",
            "TimeRulesRecipes.LocalDateTimePlusSecondsRecipe",
            "TimeRulesRecipes.LocalDateTimePlusWeeksRecipe",
            "TimeRulesRecipes.LocalDateTimePlusYearsRecipe",
            "TimeRulesRecipes.LocalTimeMinRecipe",
            "TimeRulesRecipes.LocalTimeMinusHoursRecipe",
            "TimeRulesRecipes.LocalTimeMinusMinutesRecipe",
            "TimeRulesRecipes.LocalTimeMinusNanosRecipe",
            "TimeRulesRecipes.LocalTimeMinusSecondsRecipe",
            "TimeRulesRecipes.LocalTimeOfInstantRecipe",
            "TimeRulesRecipes.LocalTimePlusHoursRecipe",
            "TimeRulesRecipes.LocalTimePlusMinutesRecipe",
            "TimeRulesRecipes.LocalTimePlusNanosRecipe",
            "TimeRulesRecipes.LocalTimePlusSecondsRecipe",
            "TimeRulesRecipes.OffsetDateTimeIsAfterRecipe",
            "TimeRulesRecipes.OffsetDateTimeIsBeforeRecipe",
            "TimeRulesRecipes.OffsetDateTimeMinusDaysRecipe",
            "TimeRulesRecipes.OffsetDateTimeMinusHoursRecipe",
            "TimeRulesRecipes.OffsetDateTimeMinusMinutesRecipe",
            "TimeRulesRecipes.OffsetDateTimeMinusMonthsRecipe",
            "TimeRulesRecipes.OffsetDateTimeMinusNanosRecipe",
            "TimeRulesRecipes.OffsetDateTimeMinusSecondsRecipe",
            "TimeRulesRecipes.OffsetDateTimeMinusWeeksRecipe",
            "TimeRulesRecipes.OffsetDateTimeMinusYearsRecipe",
            "TimeRulesRecipes.OffsetDateTimeOfInstantRecipe",
            "TimeRulesRecipes.OffsetDateTimePlusDaysRecipe",
            "TimeRulesRecipes.OffsetDateTimePlusHoursRecipe",
            "TimeRulesRecipes.OffsetDateTimePlusMinutesRecipe",
            "TimeRulesRecipes.OffsetDateTimePlusMonthsRecipe",
            "TimeRulesRecipes.OffsetDateTimePlusNanosRecipe",
            "TimeRulesRecipes.OffsetDateTimePlusSecondsRecipe",
            "TimeRulesRecipes.OffsetDateTimePlusWeeksRecipe",
            "TimeRulesRecipes.OffsetDateTimePlusYearsRecipe",
            "TimeRulesRecipes.OffsetTimeMinusHoursRecipe",
            "TimeRulesRecipes.OffsetTimeMinusMinutesRecipe",
            "TimeRulesRecipes.OffsetTimeMinusNanosRecipe",
            "TimeRulesRecipes.OffsetTimeMinusSecondsRecipe",
            "TimeRulesRecipes.OffsetTimeOfInstantRecipe",
            "TimeRulesRecipes.OffsetTimePlusHoursRecipe",
            "TimeRulesRecipes.OffsetTimePlusMinutesRecipe",
            "TimeRulesRecipes.OffsetTimePlusNanosRecipe",
            "TimeRulesRecipes.OffsetTimePlusSecondsRecipe",
            "TimeRulesRecipes.UtcClockRecipe",
            "TimeRulesRecipes.UtcConstantRecipe",
            "TimeRulesRecipes.ZeroDurationRecipe",
            "TimeRulesRecipes.ZeroPeriodRecipe",
            "TimeRulesRecipes.ZonedDateTimeMinusDaysRecipe",
            "TimeRulesRecipes.ZonedDateTimeMinusHoursRecipe",
            "TimeRulesRecipes.ZonedDateTimeMinusMinutesRecipe",
            "TimeRulesRecipes.ZonedDateTimeMinusMonthsRecipe",
            "TimeRulesRecipes.ZonedDateTimeMinusNanosRecipe",
            "TimeRulesRecipes.ZonedDateTimeMinusSecondsRecipe",
            "TimeRulesRecipes.ZonedDateTimeMinusWeeksRecipe",
            "TimeRulesRecipes.ZonedDateTimeMinusYearsRecipe",
            "TimeRulesRecipes.ZonedDateTimePlusDaysRecipe",
            "TimeRulesRecipes.ZonedDateTimePlusHoursRecipe",
            "TimeRulesRecipes.ZonedDateTimePlusMinutesRecipe",
            "TimeRulesRecipes.ZonedDateTimePlusMonthsRecipe",
            "TimeRulesRecipes.ZonedDateTimePlusNanosRecipe",
            "TimeRulesRecipes.ZonedDateTimePlusSecondsRecipe",
            "TimeRulesRecipes.ZonedDateTimePlusWeeksRecipe",
            "TimeRulesRecipes.ZonedDateTimePlusYearsRecipe",
            "AssertJBigIntegerRulesRecipes.AbstractBigIntegerAssertIsEqualToRecipe",
            "AssertJBigIntegerRulesRecipes.AbstractBigIntegerAssertIsNotEqualToRecipe",
            "AssertJBigIntegerRulesRecipes.AbstractBigIntegerAssertIsNotZeroRecipe",
            "AssertJBigIntegerRulesRecipes.AbstractBigIntegerAssertIsOneRecipe",
            "AssertJBigIntegerRulesRecipes.AbstractBigIntegerAssertIsZeroRecipe",
            "ImmutableSortedSetRulesRecipes.EmptyImmutableSortedSetRecipe",
            "ImmutableSortedSetRulesRecipes.ImmutableSortedSetBuilderRecipe",
            "ImmutableSortedSetRulesRecipes.ImmutableSortedSetNaturalOrderBuilderRecipe",
            "ImmutableSortedSetRulesRecipes.ImmutableSortedSetReverseOrderBuilderRecipe",
            "ImmutableSortedSetRulesRecipes.IterableToImmutableSortedSetRecipe",
            "ImmutableSortedSetRulesRecipes.StreamToImmutableSortedSetRecipe",
            "BigDecimalRulesRecipes.BigDecimalOneRecipe",
            "BigDecimalRulesRecipes.BigDecimalSignumIsNegativeRecipe",
            "BigDecimalRulesRecipes.BigDecimalSignumIsPositiveRecipe",
            "BigDecimalRulesRecipes.BigDecimalSignumIsZeroRecipe",
            "BigDecimalRulesRecipes.BigDecimalTenRecipe",
            "BigDecimalRulesRecipes.BigDecimalValueOfRecipe",
            "BigDecimalRulesRecipes.BigDecimalZeroRecipe",
            "PrimitiveRulesRecipes.ArraysCompareUnsignedBytesRecipe",
            "PrimitiveRulesRecipes.ArraysCompareUnsignedIntsRecipe",
            "PrimitiveRulesRecipes.ArraysCompareUnsignedLongsRecipe",
            "PrimitiveRulesRecipes.BooleanHashCodeRecipe",
            "PrimitiveRulesRecipes.ByteHashCodeRecipe",
            "PrimitiveRulesRecipes.CharacterBytesRecipe",
            "PrimitiveRulesRecipes.CharacterHashCodeRecipe",
            "PrimitiveRulesRecipes.DoubleBytesRecipe",
            "PrimitiveRulesRecipes.DoubleHashCodeRecipe",
            "PrimitiveRulesRecipes.DoubleIsFiniteRecipe",
            "PrimitiveRulesRecipes.FloatBytesRecipe",
            "PrimitiveRulesRecipes.FloatHashCodeRecipe",
            "PrimitiveRulesRecipes.FloatIsFiniteRecipe",
            "PrimitiveRulesRecipes.GreaterThanRecipe",
            "PrimitiveRulesRecipes.GreaterThanOrEqualToRecipe",
            "PrimitiveRulesRecipes.IntegerBytesRecipe",
            "PrimitiveRulesRecipes.IntegerCompareUnsignedRecipe",
            "PrimitiveRulesRecipes.IntegerDivideUnsignedRecipe",
            "PrimitiveRulesRecipes.IntegerHashCodeRecipe",
            "PrimitiveRulesRecipes.IntegerParseUnsignedIntRecipe",
            "PrimitiveRulesRecipes.IntegerParseUnsignedIntWithRadixRecipe",
            "PrimitiveRulesRecipes.IntegerRemainderUnsignedRecipe",
            "PrimitiveRulesRecipes.IntegerSignumIsNegativeRecipe",
            "PrimitiveRulesRecipes.IntegerSignumIsPositiveRecipe",
            "PrimitiveRulesRecipes.IntegerToUnsignedStringRecipe",
            "PrimitiveRulesRecipes.IntegerToUnsignedStringWithRadixRecipe",
            "PrimitiveRulesRecipes.LessThanRecipe",
            "PrimitiveRulesRecipes.LessThanOrEqualToRecipe",
            "PrimitiveRulesRecipes.LongBytesRecipe",
            "PrimitiveRulesRecipes.LongCompareUnsignedRecipe",
            "PrimitiveRulesRecipes.LongDivideUnsignedRecipe",
            "PrimitiveRulesRecipes.LongHashCodeRecipe",
            "PrimitiveRulesRecipes.LongParseUnsignedLongRecipe",
            "PrimitiveRulesRecipes.LongParseUnsignedLongWithRadixRecipe",
            "PrimitiveRulesRecipes.LongRemainderUnsignedRecipe",
            "PrimitiveRulesRecipes.LongSignumIsNegativeRecipe",
            "PrimitiveRulesRecipes.LongSignumIsPositiveRecipe",
            "PrimitiveRulesRecipes.LongToIntExactRecipe",
            "PrimitiveRulesRecipes.LongToUnsignedStringRecipe",
            "PrimitiveRulesRecipes.LongToUnsignedStringWithRadixRecipe",
            "PrimitiveRulesRecipes.ShortBytesRecipe",
            "PrimitiveRulesRecipes.ShortHashCodeRecipe",
            "JUnitRulesRecipes.ArgumentsEnumerationRecipe",
            "AssertJIteratorRulesRecipes.AssertThatHasNextRecipe",
            "AssertJIteratorRulesRecipes.AssertThatIsExhaustedRecipe",
            "StringRulesRecipes.FilterEmptyStringRecipe",
            "StringRulesRecipes.JoinStringsRecipe",
            "StringRulesRecipes.NewStringFromCharArrayRecipe",
            "StringRulesRecipes.NewStringFromCharArraySubSequenceRecipe",
            "StringRulesRecipes.OptionalNonEmptyStringRecipe",
            "StringRulesRecipes.StringIndexOfCharRecipe",
            "StringRulesRecipes.StringIndexOfStringRecipe",
            "StringRulesRecipes.StringIsEmptyRecipe",
            "StringRulesRecipes.StringIsEmptyPredicateRecipe",
            "StringRulesRecipes.StringIsNotEmptyPredicateRecipe",
            "StringRulesRecipes.StringIsNullOrEmptyRecipe",
            "StringRulesRecipes.StringLastIndexOfCharRecipe",
            "StringRulesRecipes.StringLastIndexOfCharWithIndexRecipe",
            "StringRulesRecipes.StringLastIndexOfStringRecipe",
            "StringRulesRecipes.StringLastIndexOfStringWithIndexRecipe",
            "StringRulesRecipes.StringStartsWithRecipe",
            "StringRulesRecipes.StringValueOfRecipe",
            "StringRulesRecipes.StringValueOfMethodReferenceRecipe",
            "StringRulesRecipes.SubstringRemainderRecipe",
            "StringRulesRecipes.Utf8EncodedLengthRecipe",
            "ImmutableListMultimapRulesRecipes.EmptyImmutableListMultimapRecipe",
            "ImmutableListMultimapRulesRecipes.EntryToImmutableListMultimapRecipe",
            "ImmutableListMultimapRulesRecipes.ImmutableListMultimapBuilderRecipe",
            "ImmutableListMultimapRulesRecipes.IndexIterableToImmutableListMultimapRecipe",
            "ImmutableListMultimapRulesRecipes.IterableToImmutableListMultimapRecipe",
            "ImmutableListMultimapRulesRecipes.PairToImmutableListMultimapRecipe",
            "ImmutableListMultimapRulesRecipes.StreamOfMapEntriesToImmutableListMultimapRecipe",
            "ImmutableListMultimapRulesRecipes.TransformMultimapValuesToImmutableListMultimapRecipe",
            "ImmutableListMultimapRulesRecipes.TransformMultimapValuesToImmutableListMultimap2Recipe",
            "AssertJOptionalRulesRecipes.AbstractOptionalAssertContainsSameRecipe",
            "AssertJOptionalRulesRecipes.AbstractOptionalAssertHasValueRecipe",
            "AssertJOptionalRulesRecipes.AbstractOptionalAssertIsEmptyRecipe",
            "AssertJOptionalRulesRecipes.AbstractOptionalAssertIsPresentRecipe",
            "AssertJOptionalRulesRecipes.AssertThatOptionalRecipe",
            "AssertJOptionalRulesRecipes.AssertThatOptionalHasValueMatchingRecipe",
            "AssertJOptionalRulesRecipes.AssertThatOptionalIsEmptyRecipe",
            "AssertJOptionalRulesRecipes.AssertThatOptionalIsPresentRecipe",
            "CharSequenceRulesRecipes.CharSequenceIsEmptyRecipe",
            "AssertJNumberRulesRecipes.AssertThatIsEvenRecipe",
            "AssertJNumberRulesRecipes.AssertThatIsOddRecipe",
            "AssertJNumberRulesRecipes.NumberAssertIsNegativeRecipe",
            "AssertJNumberRulesRecipes.NumberAssertIsNotNegativeRecipe",
            "AssertJNumberRulesRecipes.NumberAssertIsNotPositiveRecipe",
            "AssertJNumberRulesRecipes.NumberAssertIsPositiveRecipe",
            "WebClientRulesRecipes.BodyValueRecipe",
            "WebClientRulesRecipes.RequestHeadersUriSpecUriRecipe",
            "WebClientRulesRecipes.WebClientGetRecipe",
            "WebClientRulesRecipes.WebClientHeadRecipe",
            "WebClientRulesRecipes.WebClientOptionsRecipe",
            "WebClientRulesRecipes.WebClientPatchRecipe",
            "WebClientRulesRecipes.WebClientPostRecipe",
            "WebClientRulesRecipes.WebClientPutRecipe",
            "AssortedRulesRecipes.CheckIndexRecipe",
            "AssortedRulesRecipes.CheckIndexConditionalRecipe",
            "AssortedRulesRecipes.DisjointCollectionsRecipe",
            "AssortedRulesRecipes.DisjointSetsRecipe",
            "AssortedRulesRecipes.IterableIsEmptyRecipe",
            "AssortedRulesRecipes.IteratorGetNextOrDefaultRecipe",
            "AssortedRulesRecipes.LogicalImplicationRecipe",
            "AssortedRulesRecipes.SplitToStreamRecipe",
            "AssortedRulesRecipes.UnboundedSingleElementStreamRecipe",
            "AssertJPrimitiveRulesRecipes.AssertThatIsEqualToRecipe",
            "AssertJPrimitiveRulesRecipes.AssertThatIsGreaterThanRecipe",
            "AssertJPrimitiveRulesRecipes.AssertThatIsGreaterThanOrEqualToRecipe",
            "AssertJPrimitiveRulesRecipes.AssertThatIsLessThanRecipe",
            "AssertJPrimitiveRulesRecipes.AssertThatIsLessThanOrEqualToRecipe",
            "AssertJPrimitiveRulesRecipes.AssertThatIsNotEqualToRecipe",
            "MultimapRulesRecipes.MultimapContainsKeyRecipe",
            "MultimapRulesRecipes.MultimapContainsValueRecipe",
            "MultimapRulesRecipes.MultimapGetRecipe",
            "MultimapRulesRecipes.MultimapIsEmptyRecipe",
            "MultimapRulesRecipes.MultimapKeySetRecipe",
            "MultimapRulesRecipes.MultimapKeysStreamRecipe",
            "MultimapRulesRecipes.MultimapSizeRecipe",
            "MultimapRulesRecipes.MultimapValuesStreamRecipe",
            "AssertJBigDecimalRulesRecipes.AbstractBigDecimalAssertIsEqualByComparingToRecipe",
            "AssertJBigDecimalRulesRecipes.AbstractBigDecimalAssertIsNotEqualByComparingToRecipe",
            "NullRulesRecipes.IsNotNullRecipe",
            "NullRulesRecipes.IsNullRecipe",
            "NullRulesRecipes.IsNullFunctionRecipe",
            "NullRulesRecipes.NonNullFunctionRecipe",
            "NullRulesRecipes.RequireNonNullElseRecipe",
            "NullRulesRecipes.RequireNonNullElseGetRecipe",
            "FileRulesRecipes.FileMkDirsFileExistsRecipe",
            "FileRulesRecipes.FilesCreateTempFileInCustomDirectoryToFileRecipe",
            "FileRulesRecipes.FilesCreateTempFileToFileRecipe",
            "FileRulesRecipes.FilesReadStringRecipe",
            "FileRulesRecipes.FilesReadStringWithCharsetRecipe",
            "FileRulesRecipes.PathInstanceRecipe",
            "FileRulesRecipes.PathOfStringRecipe",
            "FileRulesRecipes.PathOfUriRecipe",
            "FileRulesRecipes.PathToFileMkDirsFilesExistsRecipe",
            "RxJava2AdapterRulesRecipes.CompletableToMonoRecipe",
            "RxJava2AdapterRulesRecipes.FlowableToFluxRecipe",
            "RxJava2AdapterRulesRecipes.FluxToFlowableRecipe",
            "RxJava2AdapterRulesRecipes.FluxToObservableRecipe",
            "RxJava2AdapterRulesRecipes.MaybeToMonoRecipe",
            "RxJava2AdapterRulesRecipes.MonoToCompletableRecipe",
            "RxJava2AdapterRulesRecipes.MonoToFlowableRecipe",
            "RxJava2AdapterRulesRecipes.MonoToMaybeRecipe",
            "RxJava2AdapterRulesRecipes.MonoToSingleRecipe",
            "RxJava2AdapterRulesRecipes.ObservableToFluxRecipe",
            "RxJava2AdapterRulesRecipes.SingleToMonoRecipe");

    @Test
    void countRecipes() {
        int success = 0;
        int fail = 0;

        var templates = new IdentityHashMap<JavaTemplate, String>();
        for (var recipeName : recipes) {
            try {
                Class<?> recipeClass = Class.forName("tech.picnic.errorprone.refasterrules." + recipeName.replace('.', '$'));
                var recipe = (Recipe) recipeClass.getConstructor().newInstance();
                var visitor = recipe.getVisitor() instanceof Preconditions.Check ? extractTargetVisitor(recipe.getVisitor()) : recipe.getVisitor();
                Arrays.stream(visitor.getClass().getDeclaredFields())
                        .filter(e -> e.getType().isAssignableFrom(JavaTemplate.class))
                        .map(e -> extractTemplate(e, visitor))
                        .forEach(e -> templates.put(e, recipeName));
                success += 1;
            } catch (Exception e) {
                fail += 1;
            }
        }

        System.out.println("Templates: " + templates.size());
        System.out.println("Success: " + success);
        System.out.println("Fail: " + fail);
    }

    @ParameterizedTest
    @FieldSource("recipes")
    void validateTemplates(String recipeName) {
//        Assert.register(new Assert.Assertions() {
//            @Override
//            public void validTree(Tree tree, String src) {
//                try {
//                    Assertions.validateTypes((SourceFile) tree, TypeValidation.all());
//                } catch (Exception e) {
//                    code.add(src);
//                    exception(e);
//                }
//            }
//
//            @Override
//            public void exception(Throwable throwable) {
//                throw new AssertionError(throwable);
//            }
//        });
        int success = 0;
        int fail = 0;

        var templates = new IdentityHashMap<JavaTemplate, String>();
        try {
            Class<?> recipeClass = Class.forName("tech.picnic.errorprone.refasterrules." + recipeName.replace('.', '$'));
            var recipe = (Recipe) recipeClass.getConstructor().newInstance();
            var visitor = recipe.getVisitor() instanceof Preconditions.Check ? extractTargetVisitor(recipe.getVisitor()) : recipe.getVisitor();
            Arrays.stream(visitor.getClass().getDeclaredFields())
                    .filter(e -> e.getType().isAssignableFrom(JavaTemplate.class))
                    .map(e -> extractTemplate(e, visitor))
                    .forEach(e -> templates.put(e, recipeName));
            success += 1;
        } catch (Exception e) {
            fail += 1;
        }

//        System.out.println("Templates: " + templates.size());
//        System.out.println("Success: " + success);
//        System.out.println("Fail: " + fail);

        testTemplates(templates);
    }

    private void testTemplates(Map<JavaTemplate, String> templates) {
        var errors = new AtomicInteger();
        rewriteRun(
                spec -> spec.recipe(RewriteTest.toRecipe(() -> new JavaIsoVisitor<>() {
                            @Override
                            public J.MethodInvocation visitMethodInvocation(J.MethodInvocation method, ExecutionContext executionContext) {
                                for (var entry : templates.entrySet()) {
                                    var template = entry.getKey();
                                    try {
                                        template.matches(getCursor());
                                    } catch (Throwable e) {
                                        errors.incrementAndGet();
                                        System.out.println("Failed for template: " + entry.getValue());
                                        System.out.println("   Code: " + template.getCode());
                                        System.out.println("   Args: <" + template.getGenericTypes().stream().sorted().collect(Collectors.joining(", ")) + ">");
                                        System.out.println();
                                        System.out.println("   Error: " + e.getMessage());
                                    }
                                }
                                return method;
                            }
                        }))
                        .parser(JavaParser.fromJavaVersion().classpath(JavaParser.runtimeClasspath())),
                java(
                        """
                                import java.util.Arrays;
                                
                                class Test {
                                    void test() {
                                        Arrays.asList(1, 2, 3);
                                    }
                                }
                                """
                )
        );

        code.forEach(e -> System.out.println(e + "\n\n"));
        assertEquals(0, errors.get());
    }

    private JavaTemplate extractTemplate(Field field, TreeVisitor<?, ExecutionContext> visitor) {
        try {
            field.setAccessible(true);
            return (JavaTemplate) field.get(visitor);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @SuppressWarnings("unchecked")
    private static TreeVisitor<?, ExecutionContext> extractTargetVisitor(TreeVisitor<?, ExecutionContext> visitor) throws IllegalAccessException, NoSuchFieldException {
        Field field = Preconditions.Check.class.getDeclaredField("v");
        field.setAccessible(true);
        return (TreeVisitor<?, ExecutionContext>) field.get(visitor);
    }
}
